version: '3.3'
services:
  db:
    build:
      ./docker/db
    hostname: db
    container_name: db
    image: dockerliweipei/wordpress:db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      LANG: C.UTF-8
    ports:
      - 3306:3306
    restart : always
  redis:
    build:
     ./docker/redis
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass "redis" --appendonly yes
    ports:
      - 6379:6379
  memcached:
    build:
     ./docker/memcached
    container_name: memcached
    image: memcached:latest
    ports:
      - 11211:11211
  nginx:
    build:
      ./docker/nginx
    hostname: nginx
    container_name: nginx
    image: dockerliweipei/wordpress:nginx
    restart: always
    volumes:
      - ./docker/nginx/tools/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/tools/web:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - fpm
     links:
      - fpm
  fpm:
    build:
      ./docker/fpm
    hostname: fpm
    container_name: fpm
    image: dockerliweipei/wordpress:fpm
    restart: always
    ports:
      - 9000:9000
