version: '3.3'
services:
  fpm:
    build:
      ./docker/fpm
    hostname: fpm
    privileged: true
    container_name: fpm
    image: dockerliweipei/wordpress:fpm
    volumes:
      - ./docker/nginx/tools/web:/var/www/html
    restart: always
    ports:
      - 9000:9000
  nginx:
    build:
      ./docker/nginx
    hostname: nginx
    privileged: true
    container_name: nginx
    image: dockerliweipei/wordpress:nginx
    restart: always
    volumes:
      - ./docker/nginx/tools/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/tools/web:/var/www/html
    ports:
      - 80:80
    links:
      - fpm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

